run:
  timeout: 3m
  issues-exit-code: 1

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gofmt:
    simplify: true
  errcheck:
    check-type-assertions: true
    check-blank: true

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0