version: "2"

run:
  timeout: 3m

issues-exit-code: 1

linters:
  default: none
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused

  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    errcheck:
      check-type-assertions: true
      check-blank: true

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0