apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: books-online-stack
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/mmorall/booksonline.git'
      targetRevision: HEAD
      path: k8s/infrastructure # Force watch the DB layer
    - repoURL: 'https://github.com/mmorall/booksonline.git'
      targetRevision: HEAD
      path: k8s/application    # Force watch the App layer
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: books-online
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true