apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chaos-mesh-system
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.chaos-mesh.org'
    targetRevision: 2.6.2
    chart: chaos-mesh
    helm:
      parameters:
        - name: chaosDaemon.runtime
          value: containerd 
        - name: chaosDaemon.socketPath
          value: /run/k3s/containerd/containerd.sock
        - name: dashboard.create
          value: "true"
        - name: scheduler.enabled
      value: "true"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: chaos-mesh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true