apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: books-online-db
  namespace: books-online
spec:
  instances: 1
  
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "1"

  storage:
    size: 10Gi
    storageClass: local-path

  bootstrap:
    initdb:
      database: booksonlinedb
      owner: appuser