apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: booksonline-api-assassin
  namespace: books-online
spec:
  schedule: "@every 2m"
  type: "PodChaos"
  historyLimit: 2
  concurrencyPolicy: Forbid
  podChaos:
    action: pod-kill
    mode: one
    selector:
      labelSelectors:
        app: booksonline-api