apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: booksonline-api-assassin
  namespace: books-online
spec:
  action: pod-kill
  mode: one
  selector:
    labelSelectors:
      app: booksonline-api
  duration: "30s"