apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: booksonline-frontend-ingress
  namespace: books-online
  annotations:
    kubernetes.io/ingress.class: traefik 
spec:
  ingressClassName: traefik
  rules:
  - host: booksonline.miguelmoral.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: booksonline-frontend-svc
            port:
              number: 80apiVersion: networking.k8s.io/v1